"""Add content reporting and background jobs

Revision ID: a58f7747954d
Revises: f2c1a9d8e3b4
Create Date: 2026-05-21 00:29:38.768405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58f7747954d'
down_revision = 'f2c1a9d8e3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###
